In [2]:
!pip install pandas numpy scikit-learn matplotlib seaborn

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.5 MB 4.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.5 MB 5.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.5 MB 5.3 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/11.5 MB 3.6 MB/s eta 0:00:03
   ---------------- ----------------------- 4.7/11.5 MB 4.6 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.5 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.5 MB 4.6 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.5 MB 4.8 MB/s eta 0:00:01
   ---------------------------- ----------- 8.1/11.5 MB 4.3 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 4.3 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 4.5 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.5 MB 4.3 MB/s eta 0:00:01
   --

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("autompg.csv")

In [7]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [8]:
df.shape

(398, 9)

In [9]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [10]:
X = df.iloc[:,[2,4]]
y = df.iloc[:,5]

In [12]:
X.head()

displacement  weight
0         307.0    3504
1         350.0    3693
2         318.0    3436
3         304.0    3433
4         302.0    3449

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 40)

In [18]:
scaler = StandardScaler().fit(X_train)

In [21]:
scaler.mean_

array([ 193.29362416, 2978.66107383])

In [22]:
scaler.scale_

array([102.4388434 , 827.30502634])

In [24]:
X_train = scaler.transform(X_train)

In [26]:
print(X_train.mean(axis = 0))

[-9.53748639e-17 -2.14593444e-16]


In [27]:
scaler = StandardScaler().fit(X_test)
X_test = scaler.transform(X_test)

In [30]:
X_test.mean(axis = 0)

array([ 8.54871729e-17, -1.09912079e-16])

AttributeError: 'numpy.ndarray' object has no attribute 'scale'